### ISSUE TITLE
Hamishe_Khazan 

### ISSUE THREAD

**Issue by Wphelp98737** [aarzilli/sandblast#2]
با سلام خدمت شما 
کانال تلگرام من همیشه خزان در ترویج و رشد آن مرا یاری و کمک کنید ، متشکرم

**Comment by aarzilli** [comment]
spam?

**Comment by Wphelp98737** [comment]
سلام و با یاد خدا 
همه بیایم در پاکسهزی و پاگ نگه داشتن دنیای مجازی یکدیگر را یاری کنیم تا مجازی ورا به آیندگان هدیه کنیم و جایی باشد مجازی برای تعلیم و تربیت 
بدرود تا در دی دیگر 
@Heresa
